export const DEFAULT_CATEGORIES = [
  { name: "Comida", icon: "🍔", color: "#FF6B6B", type: "expense" as const },
  { name: "Transporte", icon: "🚗", color: "#4ECDC4", type: "expense" as const },
  { name: "Entretenimiento", icon: "🎬", color: "#9B59B6", type: "expense" as const },
  { name: "Compras", icon: "🛒", color: "#F39C12", type: "expense" as const },
  { name: "Salud", icon: "💊", color: "#E74C3C", type: "expense" as const },
  { name: "Hogar", icon: "🏠", color: "#3498DB", type: "expense" as const },
  { name: "Servicios", icon: "📄", color: "#95A5A6", type: "expense" as const },
  { name: "Otros Gastos", icon: "📦", color: "#7F8C8D", type: "expense" as const },
  { name: "Salario", icon: "💰", color: "#27AE60", type: "income" as const },
  { name: "Freelance", icon: "💻", color: "#2ECC71", type: "income" as const },
  { name: "Inversiones", icon: "📈", color: "#16A085", type: "income" as const },
  { name: "Otros Ingresos", icon: "💵", color: "#1ABC9C", type: "income" as const },
  { name: "Transferencia", icon: "🔄", color: "#34495E", type: "transfer" as const },
];
