import {
	Activity,
	AlarmClock,
	Apple,
	Archive,
	ArrowRightLeft,
	Baby,
	BadgeDollarSign,
	Banknote,
	Barcode,
	Bath,
	Battery,
	Bed,
	Beer,
	Bell,
	Bike,
	BookOpen,
	Bookmark,
	Briefcase,
	Brush,
	Building2,
	Bus,
	BusFront,
	Calculator,
	Calendar,
	Camera,
	Candy,
	Car,
	CarFront,
	Carrot,
	Cat,
	ChartLine,
	ChartPie,
	ChefHat,
	Cherry,
	Church,
	CircleDollarSign,
	Clapperboard,
	Clock,
	Cloud,
	CloudRain,
	Coffee,
	Coins,
	Compass,
	Cookie,
	CreditCard,
	Crown,
	CupSoda,
	Dog,
	DoorOpen,
	Droplet,
	Droplets,
	Dumbbell,
	EggFried,
	Ellipsis,
	FileText,
	Film,
	Fish,
	Flag,
	Flame,
	Flower2,
	Folder,
	Footprints,
	Fuel,
	Gamepad2,
	Gavel,
	Gem,
	Gift,
	Glasses,
	Globe,
	GraduationCap,
	Hammer,
	HandCoins,
	Headphones,
	Heart,
	HeartPulse,
	Home,
	Hospital,
	Hotel,
	House,
	IceCreamCone,
	Key,
	Lamp,
	Landmark,
	Laptop,
	Leaf,
	Lightbulb,
	Lock,
	Luggage,
	Mail,
	MapPin,
	Medal,
	MessageCircle,
	Mic,
	Milk,
	Mountain,
	Music,
	Navigation,
	Notebook,
	Package,
	PaintBucket,
	Palette,
	ParkingCircle,
	PartyPopper,
	Pen,
	Percent,
	PersonStanding,
	Phone,
	PiggyBank,
	Pill,
	Pizza,
	Plane,
	Plug,
	Plus,
	Presentation,
	Receipt,
	Rocket,
	Scale,
	School,
	Scissors,
	Shield,
	Ship,
	Shirt,
	ShoppingBag,
	ShoppingCart,
	Smartphone,
	Smile,
	Snowflake,
	Sofa,
	Sparkles,
	Star,
	Stethoscope,
	Store,
	Sun,
	Syringe,
	Tag,
	Tags,
	Target,
	Tent,
	ThumbsUp,
	Ticket,
	TrainFront,
	TramFront,
	Trash2,
	TreePine,
	TrendingDown,
	TrendingUp,
	Trophy,
	Tv,
	Umbrella,
	Utensils,
	Vault,
	Wallet,
	Watch,
	Wifi,
	Wine,
	Wrench,
	Zap,
	type LucideIcon,
} from "lucide-react";

const categoryIconMap = {
	"activity": Activity,
	"alarm-clock": AlarmClock,
	"apple": Apple,
	"archive": Archive,
	"arrow-right-left": ArrowRightLeft,
	"baby": Baby,
	"badge-dollar-sign": BadgeDollarSign,
	"banknote": Banknote,
	"barcode": Barcode,
	"bath": Bath,
	"battery": Battery,
	"bed": Bed,
	"beer": Beer,
	"bell": Bell,
	"bike": Bike,
	"book-open": BookOpen,
	"bookmark": Bookmark,
	"briefcase": Briefcase,
	"brush": Brush,
	"building-2": Building2,
	"bus": Bus,
	"bus-front": BusFront,
	"calculator": Calculator,
	"calendar": Calendar,
	"camera": Camera,
	"candy": Candy,
	"car": Car,
	"car-front": CarFront,
	"carrot": Carrot,
	"cat": Cat,
	"chart-line": ChartLine,
	"chart-pie": ChartPie,
	"chef-hat": ChefHat,
	"cherry": Cherry,
	"church": Church,
	"circle-dollar-sign": CircleDollarSign,
	"clapperboard": Clapperboard,
	"clock": Clock,
	"cloud": Cloud,
	"cloud-rain": CloudRain,
	"coffee": Coffee,
	"coins": Coins,
	"compass": Compass,
	"cookie": Cookie,
	"credit-card": CreditCard,
	"crown": Crown,
	"cup-soda": CupSoda,
	"dog": Dog,
	"door-open": DoorOpen,
	"droplet": Droplet,
	"droplets": Droplets,
	"dumbbell": Dumbbell,
	"egg-fried": EggFried,
	"ellipsis": Ellipsis,
	"file-text": FileText,
	"film": Film,
	"fish": Fish,
	"flag": Flag,
	"flame": Flame,
	"flower-2": Flower2,
	"folder": Folder,
	"footprints": Footprints,
	"fuel": Fuel,
	"gamepad-2": Gamepad2,
	"gavel": Gavel,
	"gem": Gem,
	"gift": Gift,
	"glasses": Glasses,
	"globe": Globe,
	"graduation-cap": GraduationCap,
	"hammer": Hammer,
	"hand-coins": HandCoins,
	"headphones": Headphones,
	"heart": Heart,
	"heart-pulse": HeartPulse,
	"home": Home,
	"hospital": Hospital,
	"hotel": Hotel,
	"house": House,
	"ice-cream-cone": IceCreamCone,
	"key": Key,
	"lamp": Lamp,
	"landmark": Landmark,
	"laptop": Laptop,
	"leaf": Leaf,
	"lightbulb": Lightbulb,
	"lock": Lock,
	"luggage": Luggage,
	"mail": Mail,
	"map-pin": MapPin,
	"medal": Medal,
	"message-circle": MessageCircle,
	"mic": Mic,
	"milk": Milk,
	"mountain": Mountain,
	"music": Music,
	"navigation": Navigation,
	"notebook": Notebook,
	"package": Package,
	"paint-bucket": PaintBucket,
	"palette": Palette,
	"parking-circle": ParkingCircle,
	"party-popper": PartyPopper,
	"pen": Pen,
	"percent": Percent,
	"person-standing": PersonStanding,
	"phone": Phone,
	"piggy-bank": PiggyBank,
	"pill": Pill,
	"pizza": Pizza,
	"plane": Plane,
	"plug": Plug,
	"plus": Plus,
	"presentation": Presentation,
	"receipt": Receipt,
	"rocket": Rocket,
	"scale": Scale,
	"school": School,
	"scissors": Scissors,
	"shield": Shield,
	"ship": Ship,
	"shirt": Shirt,
	"shopping-bag": ShoppingBag,
	"shopping-cart": ShoppingCart,
	"smartphone": Smartphone,
	"smile": Smile,
	"snowflake": Snowflake,
	"sofa": Sofa,
	"sparkles": Sparkles,
	"star": Star,
	"stethoscope": Stethoscope,
	"store": Store,
	"sun": Sun,
	"syringe": Syringe,
	"tag": Tag,
	"tags": Tags,
	"target": Target,
	"tent": Tent,
	"thumbs-up": ThumbsUp,
	"ticket": Ticket,
	"train-front": TrainFront,
	"tram-front": TramFront,
	"trash-2": Trash2,
	"tree-pine": TreePine,
	"trending-down": TrendingDown,
	"trending-up": TrendingUp,
	"trophy": Trophy,
	"tv": Tv,
	"umbrella": Umbrella,
	"utensils": Utensils,
	"vault": Vault,
	"wallet": Wallet,
	"watch": Watch,
	"wifi": Wifi,
	"wine": Wine,
	"wrench": Wrench,
	"zap": Zap,
} as const satisfies Record<string, LucideIcon>;

export const CATEGORY_ICONS = [
	"activity",
	"alarm-clock",
	"apple",
	"archive",
	"arrow-right-left",
	"baby",
	"badge-dollar-sign",
	"banknote",
	"barcode",
	"bath",
	"battery",
	"bed",
	"beer",
	"bell",
	"bike",
	"book-open",
	"bookmark",
	"briefcase",
	"brush",
	"building-2",
	"bus",
	"bus-front",
	"calculator",
	"calendar",
	"camera",
	"candy",
	"car",
	"car-front",
	"carrot",
	"cat",
	"chart-line",
	"chart-pie",
	"chef-hat",
	"cherry",
	"church",
	"circle-dollar-sign",
	"clapperboard",
	"clock",
	"cloud",
	"cloud-rain",
	"coffee",
	"coins",
	"compass",
	"cookie",
	"credit-card",
	"crown",
	"cup-soda",
	"dog",
	"door-open",
	"droplet",
	"droplets",
	"dumbbell",
	"egg-fried",
	"ellipsis",
	"file-text",
	"film",
	"fish",
	"flag",
	"flame",
	"flower-2",
	"folder",
	"footprints",
	"fuel",
	"gamepad-2",
	"gavel",
	"gem",
	"gift",
	"glasses",
	"globe",
	"graduation-cap",
	"hammer",
	"hand-coins",
	"headphones",
	"heart",
	"heart-pulse",
	"home",
	"hospital",
	"hotel",
	"house",
	"ice-cream-cone",
	"key",
	"lamp",
	"landmark",
	"laptop",
	"leaf",
	"lightbulb",
	"lock",
	"luggage",
	"mail",
	"map-pin",
	"medal",
	"message-circle",
	"mic",
	"milk",
	"mountain",
	"music",
	"navigation",
	"notebook",
	"package",
	"paint-bucket",
	"palette",
	"parking-circle",
	"party-popper",
	"pen",
	"percent",
	"person-standing",
	"phone",
	"piggy-bank",
	"pill",
	"pizza",
	"plane",
	"plug",
	"plus",
	"presentation",
	"receipt",
	"rocket",
	"scale",
	"school",
	"scissors",
	"shield",
	"ship",
	"shirt",
	"shopping-bag",
	"shopping-cart",
	"smartphone",
	"smile",
	"snowflake",
	"sofa",
	"sparkles",
	"star",
	"stethoscope",
	"store",
	"sun",
	"syringe",
	"tag",
	"tags",
	"target",
	"tent",
	"thumbs-up",
	"ticket",
	"train-front",
	"tram-front",
	"trash-2",
	"tree-pine",
	"trending-down",
	"trending-up",
	"trophy",
	"tv",
	"umbrella",
	"utensils",
	"vault",
	"wallet",
	"watch",
	"wifi",
	"wine",
	"wrench",
	"zap",
] as const;

export type CategoryIconName = (typeof CATEGORY_ICONS)[number];

export type CategoryIconGroup = {
	label: string;
	icons: CategoryIconName[];
};

export const CATEGORY_ICON_GROUPS: CategoryIconGroup[] = [
	{
		label: "Comida y bebida",
		icons: [
			"utensils",
			"coffee",
			"cup-soda",
			"pizza",
			"beer",
			"wine",
			"chef-hat",
			"egg-fried",
			"apple",
			"carrot",
			"cherry",
			"cookie",
			"candy",
			"ice-cream-cone",
			"milk",
			"fish",
		],
	},
	{
		label: "Transporte",
		icons: [
			"car",
			"car-front",
			"bus",
			"bus-front",
			"train-front",
			"tram-front",
			"bike",
			"plane",
			"ship",
			"fuel",
			"parking-circle",
			"navigation",
			"map-pin",
			"compass",
		],
	},
	{
		label: "Hogar y servicios",
		icons: [
			"house",
			"home",
			"sofa",
			"bed",
			"lamp",
			"bath",
			"door-open",
			"key",
			"plug",
			"lightbulb",
			"droplet",
			"droplets",
			"wifi",
			"phone",
			"smartphone",
			"tv",
			"hammer",
			"wrench",
			"paint-bucket",
			"cloud",
			"cloud-rain",
			"snowflake",
			"sun",
		],
	},
	{
		label: "Compras",
		icons: [
			"shopping-cart",
			"shopping-bag",
			"store",
			"tag",
			"tags",
			"gift",
			"shirt",
			"glasses",
			"watch",
			"gem",
			"barcode",
			"package",
		],
	},
	{
		label: "Finanzas",
		icons: [
			"badge-dollar-sign",
			"circle-dollar-sign",
			"banknote",
			"coins",
			"hand-coins",
			"credit-card",
			"wallet",
			"piggy-bank",
			"landmark",
			"vault",
			"receipt",
			"calculator",
			"percent",
			"chart-line",
			"chart-pie",
			"trending-up",
			"trending-down",
			"arrow-right-left",
		],
	},
	{
		label: "Salud y bienestar",
		icons: [
			"heart-pulse",
			"heart",
			"pill",
			"syringe",
			"stethoscope",
			"hospital",
			"dumbbell",
			"footprints",
			"leaf",
			"flower-2",
		],
	},
	{
		label: "Ocio y entretenimiento",
		icons: [
			"film",
			"clapperboard",
			"gamepad-2",
			"music",
			"headphones",
			"mic",
			"party-popper",
			"ticket",
			"trophy",
			"medal",
			"star",
			"sparkles",
			"tent",
			"mountain",
			"tree-pine",
			"umbrella",
			"luggage",
			"hotel",
			"globe",
			"camera",
			"rocket",
		],
	},
	{
		label: "Trabajo y educación",
		icons: [
			"briefcase",
			"laptop",
			"presentation",
			"building-2",
			"graduation-cap",
			"school",
			"book-open",
			"notebook",
			"pen",
			"brush",
			"palette",
			"folder",
			"mail",
			"message-circle",
			"calendar",
			"clock",
			"alarm-clock",
			"bell",
			"bookmark",
			"flag",
			"target",
			"scale",
			"gavel",
			"shield",
			"lock",
		],
	},
	{
		label: "Personas y mascotas",
		icons: [
			"person-standing",
			"baby",
			"smile",
			"thumbs-up",
			"crown",
			"dog",
			"cat",
		],
	},
	{
		label: "Otros",
		icons: [
			"activity",
			"zap",
			"flame",
			"scissors",
			"church",
			"archive",
			"plus",
			"ellipsis",
		],
	},
];

const LEGACY_EMOJI_MAP: Record<string, CategoryIconName> = {
	"🍔": "utensils",
	"🚗": "car",
	"🎬": "film",
	"🛒": "shopping-cart",
	"💊": "pill",
	"🏠": "house",
	"📄": "file-text",
	"📦": "package",
	"💰": "badge-dollar-sign",
	"💻": "laptop",
	"📈": "trending-up",
	"💵": "banknote",
	"🔄": "arrow-right-left",
	"🐾": "dog",
	"✈️": "plane",
	"🎁": "gift",
	"📚": "book-open",
};

export function resolveCategoryIconName(icon: string): CategoryIconName | null {
	if (icon in categoryIconMap) {
		return icon as CategoryIconName;
	}
	return LEGACY_EMOJI_MAP[icon] ?? null;
}

type CategoryIconProps = {
	icon: string;
	size?: number;
	className?: string;
	color?: string;
};

export function CategoryIcon({
	icon,
	size = 18,
	className = "",
	color,
}: CategoryIconProps) {
	const name = resolveCategoryIconName(icon);
	if (!name) {
		return (
			<span className={className} style={{ fontSize: size * 0.85 }} aria-hidden>
				{icon}
			</span>
		);
	}

	const Icon = categoryIconMap[name];
	return (
		<Icon
			size={size}
			className={className}
			color={color}
			strokeWidth={2}
			aria-hidden
		/>
	);
}
